name: two_factor_login
description: This packages implements 2FA with OTP.
version: 0.0.1
author: Fernando Uribe
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dart_otp: ^1.3.0
  base32: 1.1.2
  qr_flutter: 3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
